### ISSUE TITLE
Playwright?

### ISSUE THREAD

**Issue by das-en** [LambdaTest/codeceptjs-lambdatest-service#3]
Hi, does this work with CodeceptJS+Playwright?

Thanks!

**Comment by Shahnawaz-Sk** [comment]
@das-en Thank you for your concern, we will soon provide support for `playwright` with `codecept-lambdatest-service`

**Comment by Shahnawaz-Sk** [comment]
Hello @das-en , we have released `1.0.4` version of `codeceptjs-lambdatest-service`. It now supports `Playwright`.
